services:
  - type: web
    name: globetrotter-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    plan: free
    region: oregon
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://db.okncjgzstqrvjhtnsgfo.supabase.co:5432/postgres?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres
      - key: SPRING_DATASOURCE_PASSWORD
        value: sedvyQ-9xuhjy-nakren
