services:
  - type: web
    name: globetrotter-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    plan: free
    region: oregon
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:6543/postgres?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres.okncjgzstqrvjhtnsgfo
      - key: SPRING_DATASOURCE_PASSWORD
        value: sedvyQ-9xuhjy-nakren
